addons:
  apt:
   packages:
    - libaugeas-dev
cache:
  bundler
bundler_args: --without system_tests
script: bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation && bundle exec rake metadata'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.5
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-6-x86_64-docker"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rake beaker
  - rvm: 2.1.5
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7-x86_64-docker"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rake beaker


notifications:
  email: false
deploy:
  provider: puppetforge
  user: CERNOps
  password:
    secure: "Wov2HagpIdyxUW8FcL9W9yQzE8se01sTA3mbKfwUaqpTYm8XllfdrmNTpEbe1V+675SUBFR546jeXAA2YrLdOXbfXNAwL1ITHg1thnd+6fGz1i0KX77mMp5Mu0V0DnN1nyQAH3q9KLPblbYlP5ETYHsw9ImkiPQCtURxSLVb/co="
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    condition: $FUTURE_PARSER = yes


